version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: node index.js

workflows:
  version: 2

  nightly:
    triggers:
      - schedule:
          cron: '0 6 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - build
